version: '3'

services:

  node-app:
    build: .
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080


  db:
    build: ./mysql
    restart: always

    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "helloworld"
      MYSQL_DATABASE: "test_Process"
      MYSQL_TCP_PORT: "3307"




